In [7]:
import pandas as pd

In [11]:
df_tr = pd.read_csv('../exam2/data/train_need_aggregate.csv')

In [16]:
df_tr['EventId'].values


array([   1,    1,    1, ..., 1142, 1143,    1])

In [12]:
from sklearn.preprocessing import OneHotEncoder


In [13]:
onehot = OneHotEncoder(handle_unknown='ignore')

In [14]:
onehot.fit(df_tr['EventId'].unique().reshape(-1, 1))

OneHotEncoder(handle_unknown='ignore')

In [13]:
import pickle

In [14]:
with open('./onehotencoder.pkl', 'wb') as f:
    pickle.dump(onehot, f)

In [7]:
df_te = pd.read_csv('../exam2/data/test_need_aggregate.csv')

In [8]:
df_te['EventId'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [8]:
import torch

In [9]:
task = 'train'

In [22]:
data = onehot.transform(pd.read_csv(f'../exam2/data/{task}_need_aggregate.csv')['EventId'].values.reshape(-1, 1))

In [23]:
data

<52289x1143 sparse matrix of type '<class 'numpy.float64'>'
	with 52289 stored elements in Compressed Sparse Row format>

In [15]:
data = torch.tensor(
            onehot.transform(
                pd.read_csv(f"../exam2/data/{task}_need_aggregate.csv")[
                    "EventId"
                ].values.reshape(-1, 1)
            ).toarray()
        )

In [16]:
data

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [1., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)

In [18]:
data.unfold(0, 1143 * 5, 1)

tensor([[[1., 1., 1.,  ..., 1., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 1., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0., 

In [28]:
data.size()

torch.Size([52289, 1143])

In [4]:
from model import dataset

In [5]:
tr = dataset()

In [3]:
tr.features()

1143

In [6]:

len(tr)


52285

In [7]:
from tqdm import tqdm

In [ ]:
tqdm()

In [3]:
from model import dataset

In [7]:
dataset_tr = dataset(task='train')

In [2]:
dataset_tr = dataset(task='train')

NameError: name 'data' is not defined

In [3]:
len(dataset_tr)

41826

In [4]:
dataset_tr[-1]

NameError: name 'window_size' is not defined

In [1]:
from model import Model

In [2]:
import torch

In [8]:
model = Model(dataset_tr.features())

In [10]:
model.load_state_dict(torch.load("./model", map_location=torch.device('cpu')))

<All keys matched successfully>

In [11]:
torch.save(model.state_dict(), './model')

In [6]:
model

Model(
  (lstm_in): LSTM(1143, 2286, batch_first=True)
  (dnn_out): Linear(in_features=2286, out_features=1143, bias=True)
)

In [4]:
dataset_ev = dataset(task='evaluate', step_size=2)

Loading and Preprocessing Data(evaluate): 100%|█████████▉| 5229/5232 [00:00<00:00, 385536.51it/s]

41826 52289


In [4]:
dataset_ev = dataset(task='evaluate', step_size=2)

In [5]:
len(dataset_ev)

5229

In [5]:
len(dataset_ev)

5229

In [8]:
(52289 - 41826 - 5) // 2

5229

In [7]:
dataset_ev[5228]


{'x': tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.]]),
 'y': tensor([0, 0, 0,  ..., 0, 0, 1])}

In [8]:
import torch

In [13]:
torch.empty(3, dtype=torch.long).random_(5)

tensor([0, 3, 4])

In [14]:
torch.randn(3, 5, requires_grad=True)

tensor([[ 0.2180, -1.1164, -0.7758, -0.6159,  0.6157],
        [ 1.1255,  0.5107,  0.4546,  0.1442, -1.8434],
        [ 0.0235, -1.0156,  0.1819, -0.2908, -1.1125]], requires_grad=True)

# predict

In [1]:
import os
import torch
from model import Model
from model import dataset

In [2]:
from torch.utils.data import DataLoader

In [3]:
win = 22

In [4]:
dataset_te = dataset(task='test', window_size=win, evaluate_ratio=0)
model = Model(dataset_te.features())

In [5]:
if os.path.exists('./model/model_best'):
    model.load_state_dict(torch.load("./model/model_best", map_location=torch.device('cpu')))
elif os.path.exists('./model/model'):
    model.load_state_dict(torch.load("./model/model", map_location=torch.device('cpu')))
else:
    print('no trained model to load')
    
    

In [6]:
loader_te = DataLoader(
        dataset=dataset_te, shuffle=False, num_workers=1, batch_size=1024
)

In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
report = pd.read_csv('../exam2/data/test_need_aggregate.csv')
report

datetime  EventId
0      2017-05-14 19:39:01.445        1
1      2017-05-14 19:39:01.650        1
2      2017-05-14 19:39:02.007        2
3      2017-05-14 19:39:02.924        1
4      2017-05-14 19:39:03.166        3
...                        ...      ...
18429  2017-05-14 21:56:20.169      615
18430  2017-05-14 21:56:20.311        8
18431  2017-05-14 21:56:25.365        6
18432  2017-05-14 21:56:25.366        7
18433  2017-05-14 21:56:25.531        8

[18434 rows x 2 columns]

In [10]:
with torch.no_grad():
    model.eval()
    pred = []
    for s, batch in enumerate(loader_te):
        pred.append(model(batch['x']))
    
    prob = torch.cat(pred, dim=0)
    

In [11]:
prob.size()

torch.Size([18412, 1143])

In [12]:
anomaly_prob = []
confidence = []

In [13]:
for record, p in zip(list(report.EventId[win:] - 1), prob.numpy()):
    anomaly_prob.append((1 + max(p) - 2 * p[record]) / 2)
    confidence.append((1 - max(p)))


In [14]:
report['conf'] = [1 for i in range(win)] + confidence
report['anomaly_prob'] = [0 for i in range(win)]+anomaly_prob

In [15]:
report

datetime  EventId      conf  anomaly_prob
0      2017-05-14 19:39:01.445        1  1.000000      0.000000
1      2017-05-14 19:39:01.650        1  1.000000      0.000000
2      2017-05-14 19:39:02.007        2  1.000000      0.000000
3      2017-05-14 19:39:02.924        1  1.000000      0.000000
4      2017-05-14 19:39:03.166        3  1.000000      0.000000
...                        ...      ...       ...           ...
18429  2017-05-14 21:56:20.169      615  0.446674      0.776142
18430  2017-05-14 21:56:20.311        8  0.461253      0.756579
18431  2017-05-14 21:56:25.365        6  0.445496      0.739901
18432  2017-05-14 21:56:25.366        7  0.446956      0.775143
18433  2017-05-14 21:56:25.531        8  0.446673      0.763935

[18434 rows x 4 columns]

In [16]:
report.describe()

EventId          conf  anomaly_prob
count  18434.000000  18434.000000  18434.000000
mean      51.890800      0.449978      0.491276
std      129.986419      0.019301      0.272143
min        1.000000      0.445274      0.000000
25%        1.000000      0.448449      0.224254
50%        1.000000      0.448509      0.229447
75%       14.000000      0.449156      0.771706
max      615.000000      1.000000      0.777284

In [17]:
report[
    ((report['anomaly_prob'] > np.quantile(report['anomaly_prob'], .997)) & (report['anomaly_prob'] > 0.7))
]

datetime  EventId      conf  anomaly_prob
232    2017-05-14 19:40:50.400       19  0.445300      0.777248
909    2017-05-14 19:45:56.295       19  0.445276      0.777260
988    2017-05-14 19:46:27.098       55  0.445377      0.777140
1255   2017-05-14 19:48:31.297       64  0.445333      0.777247
1443   2017-05-14 19:50:01.301       19  0.445275      0.777261
1622   2017-05-14 19:51:15.862       77  0.445438      0.777165
1710   2017-05-14 19:51:57.609       78  0.445315      0.777284
2190   2017-05-14 19:55:26.322       95  0.445299      0.777241
2950   2017-05-14 20:01:11.154       19  0.445276      0.777260
3034   2017-05-14 20:01:41.233      121  0.445299      0.777197
3517   2017-05-14 20:05:16.304       19  0.445275      0.777261
4044   2017-05-14 20:09:12.356       28  0.445299      0.777135
4527   2017-05-14 20:12:46.169      169  0.445300      0.777130
4873   2017-05-14 20:15:27.886       19  0.445299      0.777248
5150   2017-05-14 20:17:31.348       19  0.445300      0.777248
5903   2017-05-14 20:23:06.568      214  0.445299      0.777224
6107   2017-05-14 20:24:36.298       19  0.445274      0.777261
6750   2017-05-14 20:29:32.129       28  0.445274      0.777148
7037   2017-05-14 20:31:36.151       28  0.445274      0.777148
7210   2017-05-14 20:32:50.325      258  0.445315      0.777258
7302   2017-05-14 20:33:40.126       28  0.445274      0.777148
7381   2017-05-14 20:34:11.169      262  0.445389      0.777137
7876   2017-05-14 20:37:51.301       19  0.445276      0.777260
8137   2017-05-14 20:39:45.520      286  0.445299      0.777130
8404   2017-05-14 20:41:48.133       28  0.445300      0.777135
8420   2017-05-14 20:41:50.326      295  0.445315      0.777157
9513   2017-05-14 20:50:01.916       28  0.445314      0.777128
9790   2017-05-14 20:52:07.404       19  0.445300      0.777248
10195  2017-05-14 20:55:08.163       19  0.445275      0.777261
10352  2017-05-14 20:56:10.493      360  0.445380      0.777149
11590  2017-05-14 21:05:16.352       19  0.445299      0.777248
11703  2017-05-14 21:06:00.850      402  0.445432      0.777134
12019  2017-05-14 21:08:34.126       28  0.445274      0.777148
12840  2017-05-14 21:14:50.888      438  0.445299      0.777243
12914  2017-05-14 21:15:29.373       19  0.445299      0.777248
13196  2017-05-14 21:17:32.360       19  0.445299      0.777248
13213  2017-05-14 21:17:36.204      448  0.445299      0.777224
13410  2017-05-14 21:19:01.391      454  0.445299      0.777154
13601  2017-05-14 21:20:34.303       19  0.445274      0.777261
13746  2017-05-14 21:21:36.371       19  0.445299      0.777248
13895  2017-05-14 21:22:30.402      469  0.445299      0.777240
14174  2017-05-14 21:24:36.202      478  0.445316      0.777190
14192  2017-05-14 21:24:46.294       28  0.445276      0.777147
14750  2017-05-14 21:28:52.299       28  0.445275      0.777147
14924  2017-05-14 21:30:06.062      502  0.445299      0.777143
15291  2017-05-14 21:32:50.325      516  0.445299      0.777171
15300  2017-05-14 21:32:56.296       28  0.445274      0.777148
15668  2017-05-14 21:35:35.953      526  0.445316      0.777218
15757  2017-05-14 21:36:16.222      529  0.445299      0.777244
16426  2017-05-14 21:41:11.303       28  0.445274      0.777148
16976  2017-05-14 21:45:17.301       28  0.445274      0.777148
17068  2017-05-14 21:46:05.176       19  0.445275      0.777261
17327  2017-05-14 21:48:07.129       19  0.445299      0.777248
17612  2017-05-14 21:50:11.361       19  0.445300      0.777248
17630  2017-05-14 21:50:15.774      586  0.445299      0.777140
18419  2017-05-14 21:56:19.170       19  0.445299      0.777248

In [18]:
157 / 52289

0.003002543556006043

In [19]:
report['anomaly'] = [0 for x in report.index]
report

datetime  EventId      conf  anomaly_prob  anomaly
0      2017-05-14 19:39:01.445        1  1.000000      0.000000        0
1      2017-05-14 19:39:01.650        1  1.000000      0.000000        0
2      2017-05-14 19:39:02.007        2  1.000000      0.000000        0
3      2017-05-14 19:39:02.924        1  1.000000      0.000000        0
4      2017-05-14 19:39:03.166        3  1.000000      0.000000        0
...                        ...      ...       ...           ...      ...
18429  2017-05-14 21:56:20.169      615  0.446674      0.776142        0
18430  2017-05-14 21:56:20.311        8  0.461253      0.756579        0
18431  2017-05-14 21:56:25.365        6  0.445496      0.739901        0
18432  2017-05-14 21:56:25.366        7  0.446956      0.775143        0
18433  2017-05-14 21:56:25.531        8  0.446673      0.763935        0

[18434 rows x 5 columns]

In [20]:
report.loc[((report['anomaly_prob'] > np.quantile(report['anomaly_prob'], .997)) & (report['anomaly_prob'] > 0.7)), 'anomaly'] = 1

In [21]:
report

datetime  EventId      conf  anomaly_prob  anomaly
0      2017-05-14 19:39:01.445        1  1.000000      0.000000        0
1      2017-05-14 19:39:01.650        1  1.000000      0.000000        0
2      2017-05-14 19:39:02.007        2  1.000000      0.000000        0
3      2017-05-14 19:39:02.924        1  1.000000      0.000000        0
4      2017-05-14 19:39:03.166        3  1.000000      0.000000        0
...                        ...      ...       ...           ...      ...
18429  2017-05-14 21:56:20.169      615  0.446674      0.776142        0
18430  2017-05-14 21:56:20.311        8  0.461253      0.756579        0
18431  2017-05-14 21:56:25.365        6  0.445496      0.739901        0
18432  2017-05-14 21:56:25.366        7  0.446956      0.775143        0
18433  2017-05-14 21:56:25.531        8  0.446673      0.763935        0

[18434 rows x 5 columns]

In [22]:
import swifter

In [23]:
import pendulum as pdl


In [24]:
report['datetime'] = (
        report['datetime']
        .swifter
        .apply(
            lambda x: pdl.parse(x).format('YYYY-MM-DD HH:mm:00')
        )
    )

In [25]:
report_agg = (
        report
#         .groupby('datetime')['EventId']
#         .apply(list)
#         .reset_index(name='EventId')
    
        .groupby('datetime')['anomaly']
        .apply(list)
#         .apply(lambda x: x.count(1))
        .apply(max)
        .reset_index(name='anomaly')
        
    )
report_agg

datetime  anomaly
0    2017-05-14 19:39:00        0
1    2017-05-14 19:40:00        1
2    2017-05-14 19:41:00        0
3    2017-05-14 19:42:00        0
4    2017-05-14 19:43:00        0
..                   ...      ...
133  2017-05-14 21:52:00        0
134  2017-05-14 21:53:00        0
135  2017-05-14 21:54:00        0
136  2017-05-14 21:55:00        0
137  2017-05-14 21:56:00        1

[138 rows x 2 columns]

In [26]:
pd.merge(pd.read_csv('../exam2/result/test.csv'), report_agg, how='left', on=['datetime'])


datetime                                            EventId  \
0    2017-05-14 19:39:00  [1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, ...   
1    2017-05-14 19:40:00  [1, 6, 7, 1, 8, 1, 1, 1, 1, 9, 1, 3, 15, 24, 2...   
2    2017-05-14 19:41:00  [8, 8, 8, 1, 1, 14, 29, 16, 30, 18, 30, 18, 29...   
3    2017-05-14 19:42:00  [1, 1, 1, 1, 1, 3, 3, 1, 23, 1, 6, 7, 8, 1, 1,...   
4    2017-05-14 19:43:00  [6, 7, 35, 35, 8, 38, 1, 38, 1, 13, 1, 8, 8, 8...   
..                   ...                                                ...   
133  2017-05-14 21:52:00  [1, 1, 1, 1, 1, 1, 6, 7, 8, 3, 3, 1, 23, 1, 1,...   
134  2017-05-14 21:53:00  [6, 7, 1, 8, 1, 1, 1, 598, 1, 598, 1, 598, 598...   
135  2017-05-14 21:54:00  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 23,...   
136  2017-05-14 21:55:00  [6, 7, 8, 1, 1, 1, 1, 607, 1, 607, 1, 6, 7, 8,...   
137  2017-05-14 21:56:00  [613, 1, 1, 3, 1, 1, 1, 1, 1, 1, 6, 7, 8, 3, 3...   

     anomaly  
0          0  
1          1  
2          0  
3          0  
4          0  
..       ...  
133        0  
134        0  
135        0  
136        0  
137        1  

[138 rows x 3 columns]

In [27]:
report_agg[report_agg.anomaly == 1]

datetime  anomaly
0    2017-05-16 00:00:00        1
2    2017-05-16 00:02:00        1
8    2017-05-16 00:08:00        1
9    2017-05-16 00:09:00        1
11   2017-05-16 00:11:00        1
..                   ...      ...
365  2017-05-16 06:05:00        1
376  2017-05-16 06:16:00        1
377  2017-05-16 06:17:00        1
378  2017-05-16 06:18:00        1
382  2017-05-16 06:22:00        1

[118 rows x 2 columns]

In [28]:
report_agg[report_agg.anomaly == 0]

datetime  anomaly
1    2017-05-16 00:01:00        0
3    2017-05-16 00:03:00        0
4    2017-05-16 00:04:00        0
5    2017-05-16 00:05:00        0
6    2017-05-16 00:06:00        0
..                   ...      ...
380  2017-05-16 06:20:00        0
381  2017-05-16 06:21:00        0
383  2017-05-16 06:23:00        0
384  2017-05-16 06:24:00        0
385  2017-05-16 06:25:00        0

[268 rows x 2 columns]