In [7]:
import pandas as pd

In [11]:
df_tr = pd.read_csv('../exam2/data/train_need_aggregate.csv')

In [16]:
df_tr['EventId'].values


array([   1,    1,    1, ..., 1142, 1143,    1])

In [12]:
from sklearn.preprocessing import OneHotEncoder


In [13]:
onehot = OneHotEncoder(handle_unknown='ignore')

In [14]:
onehot.fit(df_tr['EventId'].unique().reshape(-1, 1))

OneHotEncoder(handle_unknown='ignore')

In [13]:
import pickle

In [14]:
with open('./onehotencoder.pkl', 'wb') as f:
    pickle.dump(onehot, f)

In [7]:
df_te = pd.read_csv('../exam2/data/test_need_aggregate.csv')

In [8]:
df_te['EventId'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [8]:
import torch

In [9]:
task = 'train'

In [22]:
data = onehot.transform(pd.read_csv(f'../exam2/data/{task}_need_aggregate.csv')['EventId'].values.reshape(-1, 1))

In [23]:
data

<52289x1143 sparse matrix of type '<class 'numpy.float64'>'
	with 52289 stored elements in Compressed Sparse Row format>

In [15]:
data = torch.tensor(
            onehot.transform(
                pd.read_csv(f"../exam2/data/{task}_need_aggregate.csv")[
                    "EventId"
                ].values.reshape(-1, 1)
            ).toarray()
        )

In [16]:
data

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [1., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)

In [18]:
data.unfold(0, 1143 * 5, 1)

tensor([[[1., 1., 1.,  ..., 1., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 1., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[1., 1., 1.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[1., 1., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0., 

In [28]:
data.size()

torch.Size([52289, 1143])

In [4]:
from model import dataset

In [5]:
tr = dataset()

In [3]:
tr.features()

1143

In [6]:

len(tr)


52285

In [7]:
from tqdm import tqdm

In [ ]:
tqdm()

In [3]:
from model import dataset

In [7]:
dataset_tr = dataset(task='train')

In [2]:
dataset_tr = dataset(task='train')

NameError: name 'data' is not defined

In [3]:
len(dataset_tr)

41826

In [4]:
dataset_tr[-1]

NameError: name 'window_size' is not defined

In [1]:
from model import Model

In [2]:
import torch

In [6]:
model = Model(dataset_tr.features())

NameError: name 'dataset_tr' is not defined

In [3]:
model.load_state_dict(torch.load("./model"))

NameError: name 'model' is not defined

In [6]:
model

Model(
  (lstm_in): LSTM(1143, 2286, batch_first=True)
  (dnn_out): Linear(in_features=2286, out_features=1143, bias=True)
)

In [4]:
dataset_ev = dataset(task='evaluate', step_size=2)

Loading and Preprocessing Data(evaluate): 100%|█████████▉| 5229/5232 [00:00<00:00, 385536.51it/s]

41826 52289


In [4]:
dataset_ev = dataset(task='evaluate', step_size=2)

In [5]:
len(dataset_ev)

5229

In [5]:
len(dataset_ev)

5229

In [8]:
(52289 - 41826 - 5) // 2

5229

In [7]:
dataset_ev[5228]


{'x': tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.]]),
 'y': tensor([0, 0, 0,  ..., 0, 0, 1])}

In [8]:
import torch

In [13]:
torch.empty(3, dtype=torch.long).random_(5)

tensor([0, 3, 4])

In [14]:
torch.randn(3, 5, requires_grad=True)

tensor([[ 0.2180, -1.1164, -0.7758, -0.6159,  0.6157],
        [ 1.1255,  0.5107,  0.4546,  0.1442, -1.8434],
        [ 0.0235, -1.0156,  0.1819, -0.2908, -1.1125]], requires_grad=True)